export const WEBHOOK_URL =
  'https://coolblu.app.n8n.cloud/webhook/apollo-clay-instantly';

export const INDUSTRIES = [
  'Construction',
  'Manufacturing',
  'Transportation & Logistics',
  'Healthcare Services',
  'Professional Services',
  'Retail',
  'Wholesale Distribution',
  'Food & Beverage',
  'Real Estate',
  'Auto Services',
  'Home Services',
  'Technology',
  'Financial Services',
  'Other',
] as const;

export const US_STATES = [
  'All United States',
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
] as const;

export const COMPANY_SIZES = [
  '1-10',
  '11-20',
  '21-50',
  '51-100',
  '101-200',
  '201-500',
  '501-1000',
  '1001-5000',
] as const;

export const CONTACT_TARGETS = [
  'Owner',
  'CEO',
  'President',
  'Owner,CEO,President',
  'CEO,CFO,COO',
] as const;

export const LEAD_COUNTS = ['25', '50', '100', '150', '200'] as const;

export const REVENUE_OPTIONS = [
  'Any',
  '$1M-$5M',
  '$5M-$10M',
  '$10M-$25M',
  '$25M-$50M',
  '$50M-$100M',
  '$100M+',
] as const;

export const ONE_CLICK_INDUSTRIES = [
  'E-Commerce',
  'Legal',
  'Real Estate',
  'Staffing and Recruiting',
  'Marketing and Advertising',
] as const;

export const ONE_CLICK_INCLUDE_KEYWORDS = [
  'ecommerce store',
  'online retail',
  'shopify seller',
  'amazon seller',
  'DTC brand',
  'dropshipping',
  'law firm',
  'legal services',
  'attorney',
  'law practice',
  'legal counsel',
  'immigration law',
  'personal injury',
  'real estate agency',
  'property management',
  'real estate brokerage',
  'commercial real estate',
  'real estate investment',
  'realtor',
  'staffing agency',
  'recruitment agency',
  'temp staffing',
  'workforce solutions',
  'talent acquisition',
  'employment agency',
  'marketing agency',
  'digital agency',
  'creative agency',
  'advertising agency',
  'PR agency',
  'media agency',
  'social media agency',
  'SEO agency',
  'bookkeeping',
  'accounting services',
  'financial reporting',
  'CFO services',
  'outsourced accounting',
  'tax preparation',
  'payroll services',
] as const;

export const ONE_CLICK_EXCLUDE_KEYWORDS = [
  'accounting firm',
  'CPA firm',
  'bookkeeping service',
  'enterprise',
  'Fortune 500',
] as const;
